### ISSUE TITLE
Open This Lab Doesn't Work

### ISSUE THREAD

**Issue by christinamcmahon** [learn-co-curriculum/ruby-oo-fundamentals-classes-and-instances-lab#1]
The authenticity of host 'github.com (192.30.255.112)' can't be established.
RSA key fingerprint is SHA256....
Are you sure you want to continue connecting (yes/no)? yes

**Comment by rrcobb** [comment]
This looks like it's an issue with your configuration, and not with this lab in particular. You might find https://help.github.com/en/github/authenticating-to-github/testing-your-ssh-connection helpful if you are still seeing this problem.

If you think the problem is with this lab (for instance, if it doesn't happen for other labs, and only for this one) please re-open the issue. If you do, it would be helpful for us to have more information about the steps that we can take to reproduce the error. In particular, what steps you are taking to open the lab, and what error output you are seeing. Thank you!
